### PR TITLE
[Infrastructure] CGroups

### PR DESCRIPTION
**Pull request by rrcomtech**
Implements a script, that allows to run CGroups.

### CODE REVIEW

**Comment by rrcomtech** [comment]
No further contribution.

**Comment by phoeinx** [comment]
Reopening to evaluate script for further benchmarks.

**Comment by rrcomtech** [comment]
@phoeinx Is this still active?

**Comment by rrcomtech** [comment]
@mweisgut @Bouncner @klauck FYI

@phoeinx 
We want to know how to limit our memory in order to see effects of used-up memory, even if we do not get TPCH with high scale factors running. 

💡 Therefore, we want to make sure, how to limit the memory. 

So far, we found [here](https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt), that we should have the parameter `memory.limit_in_bytes` to limit the memory consumption. Even though, on my local system (Ubuntu 22.04), only the following parameters are available:

image

Therefore, I'd suggest going with `memory.max`. It is described [here](https://facebookmicrosites.github.io/cgroup2/docs/memory-controller.html).

> `memory.max` is the memory usage hard limit, acting as the final protection mechanism: If a cgroup's memory usage reaches this limit and can't be reduced, the system OOM killer is invoked on the cgroup. Under certain circumstances, usage may go over the memory.high limit temporarily. When the high limit is used and monitored properly, memory.max serves mainly to provide the final safety net. The default is max.

**Comment by Bouncner** [comment]
As far as I understand the documentation, Ubuntu 22.04 has a recent enough Kernel to provide cgroups v2 (`limit_in_bytes` is v1).
From the description, I assume it to be pretty much what we want.

**Comment by Bouncner** [comment]
Looking at the script, I am wondering if we really want to adapt all benchmarks in this shell script or rather us it as a wrapper, which gets two parameter: cgroup limit and command to execute.

**Comment by Bouncner** [comment]
If we have such a script: what about printing some useful information coming out of `memory.stat` (e.g., "file_mapped: Amount of cached filesystem data mapped with mmap()") in a loop?

**Comment by phoeinx** [comment]
> As far as I understand the documentation, Ubuntu 22.04 has a recent enough Kernel to provide cgroups v2 (`limit_in_bytes` is v1).
> From the description, I assume it to be pretty much what we want.

You mean that `memory.max` is what we want, right? Let's try it - I am not sure what exactly: "[if the memory] can't be reduced" means and if we could risk having our processes terminated if we don't set a `memory.high` limit. But let's try it with `memory.max` only first, just as a thought if our processes get killed.

**Comment by phoeinx** [comment]
Is contained in other #122

**Pull request closed without merging**
