### PR TITLE
Update cmake.yml to run build jobs in parallel.

### PR DESCRIPTION
**Pull request by phoeinx**

### CODE REVIEW

**Review by SanJSp — APPROVED** [review]
Looks great :) Well spotted!
I guess the relevant changes are only in the cmake.yml, the rest seems to be formatting/Tobias umap solution

If anybody else stumbles over the -j flag, here is a quick explanation:


ninja -j 2 specifies that the ninja build system should use two jobs while building the project.

The -j flag stands for "jobs", and it tells ninja to build multiple targets in parallel. The value provided to -j specifies the maximum number of targets that should be built concurrently.

In this case, ninja -j 2 is telling ninja to use two jobs while building the project. This means that ninja will build at most two targets at the same time, potentially speeding up the build process. The actual number of targets built concurrently will depend on the available resources on the machine and the dependencies between the targets.

**Comment by rrcomtech** [comment]
But isn't Ninja determining the appropriate number of jobs already by itself? According to the [Ninja Manual](https://ninja-build.org/manual.html) (see Section "Running Ninja"), it is stated, that usually one does not need to pass the `-j` option. So we might limit ourselves, should Azure give us some more resources.

**Comment by phoeinx** [comment]
Hi, I'll be back at my laptop this evening, but as a short explanation: This was to experiment with threads to see if it actually makes the CI faster. (Doesn't seem to be the case with a build time of 32m)
A second, but more time-intensive approach would be to introduce caching of our cmake state (as its done locally). Would decrease CI time drastically and perhaps would be interesting when we start coding in hyrise.

**Comment by phoeinx** [comment]
Let's focus on other things than making the CI faster for now. (And maybe get back to caching in the CI later.)

**Pull request closed without merging**
